---
# tasks file for python
- name: Check that the /usr/local/bin/python3.7 exists
  stat:
    path: /usr/local/bin/python3.7
  tags: python
  register: python_result

- name: Install packages needed for installing Python
  apt: pkg={{ item }}
  with_items:
    - wget
    - xz-utils
    - build-essential
    - libsqlite3-dev
    - libreadline-dev
    - libssl-dev
    - openssl
  tags: packages, python
  when: python_result.stat.exists == False

- name: Extract python 3.7.6 into /tmp
  unarchive:
    src: https://www.python.org/ftp/python/3.7.6/Python-3.7.6.tar.xz
    dest: /tmp/
    remote_src: yes
  tags: packages, python
  become: yes

- name: Configure python 3.7.6
  shell: ./configure chdir=/tmp/Python-3.7.6
  tags: packages, python
  when: python_result.stat.exists == False
  become: yes

- name: Make
  shell: make chdir=/tmp/Python-3.7.6
  tags: packages, python
  when: python_result.stat.exists == False
  become: yes

- name: Install Python 3.7.6
  shell: make install chdir=/tmp/Python-3.7.6
  become: yes
  become_user: root
  tags: packages, python
  when: python_result.stat.exists == False

- name: Remove tmp files used for Python 3.7.6 installation
  file: path={{ item }} state=absent
  with_items:
    - /tmp/Python.tar.xz
    - /tmp/Python-3.7.6
  tags: packages, python
  when: python_result.stat.exists == False
  become: yes

